#!/bin/bash

##
# clang/clang++ wrapper for cross-compiling.
# This script is invoked by xcrun upon calling clang.
##

TOOL=`../src/xcrun/xcrun -sdk / -find ${0}`
SDKROOT=`../src/xcrun/xcrun --show-sdk-path`
TARGET_TRIPLE=`../src/xcrun/xcrun --show-sdk-target-triple`
TOOLCHAIN_DIR=`../src/xcrun/xcrun --show-sdk-toolchain-path`

${TOOL} -target ${TARGET_TRIPLE} -isysroot ${SDKROOT} -B${TOOLCHAIN_DIR}/usr/bin "${@}"

exit ${?}
