//
// Created by Diego Magdaleno on 11/14/20.
//

#ifndef MICROXCODE_ERRORS_H
#define MICROXCODE_ERRORS_H
enum microxcode_error_state_t {
	NOT_AUTHENTIC = 3, //3
	UNABLE_TO_VALIDATE, //4
	NOT_VALID, //5
	UNABLE_TO_GET_DEV_PATH, //6
	ERROR_GETTING_TOOLCHAIN,
	ERROR_GETTING_SDK,
	UNSUPPORTED_PLATFORM,
	ERROR_ALLOCATING_MEMORY,
	ERROR_GETTING_DEFAULT_CONFIG,
	RUNNING_COMMAND_ERROR,
	PROGRAM_NOT_FOUND,
	INVALID_KEY_PARSED,
	EXECUTION_ERROR,
	// Successful operations start at 30
	SUCCESFUL_OPERATION = 30,

};
#endif //MICROXCODE_ERRORS_H
